# -*- coding: utf-8 -*-
"""M1PA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bula5CwnueCCg26w0SRS1Pyac0lreVV9
"""

# PalmerPenguins.py
# Parrish Robinson
# 9/27/26
# Introduces the Palmer Penguin species
# Constants representing the species and count

SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

# output the species name with introductory text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP +"!")
print("\t" + SP_GENTOO +"!")
print("and last but not least...")
print("\t" + SP_ADELIE +"!")
print()
print("There are a total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")